---
- name: Install Jenkins
  hosts: jenkins
  remote_user: ec2-user

  tasks:
  - name: Install docker
    become: yes
    ansible.builtin.yum:
      name: docker.x86_64
      state: latest
  - name: Install dependencies
      ansible.builtin.command: pip3 install requests docker
  - name: Start docker service
    become: yes
    ansible.builtin.systemd:
      state: started
      name: docker
  - name: Run Jenkins container
    become: yes
    docker_container:
      name: jenkins
      image: "jenkins/jenkins:lts-jdk11"
      state: started
      ports:
        - "80:8080"
        - "50000:50000"
      volumes:
        - "jenkins_home:/home/ec2-user/"
