---
- name: Update Jenkins config
  hosts: jenkins
  remote_user: ec2-user

  tasks:
  - name: Copy jcasc files
    ansible.builtin.copy:
      src: ../configs/jenkins/
      dest: ~/jenkins_home
      force: yes
      owner: ec2-user
  - name: Restart Jenkins container
    docker_container:
      name: jenkins
      image: "tlattice.jfrog.io/infra/jenkins_jcasc:1.1"
      state: started
      restart: yes
      ports:
        - "80:8080"
      volumes:
        - "jenkins_home:/home/ec2-user/jenkins_home"
      env:
        CASC_JENKINS_CONFIG: "/home/ec2-user/jenkins_home"
